### PR TITLE
Igor Pro 6 support

### PR DESCRIPTION
**Pull request by nsulmol**
This set of commits modifies zeromq-xop *very slightly* in order to support Igor6 and Igor7. Here I list the major things that changed.

To compile:
- We modify the ZeroMQErrorCodes to be prefix ZMQ instead of ZeroMQ. There was 1 variable that was larger than the Igor6 variable size limit of 31 characters :(.
- We modify XOP_MINIMUM_IGORVERSION to be 637 if IGOR6 is true. It could be 620, but we are setting it to the latest to force users a bit here.
- For zeromq_interop.ipf, we update #pragma IgorVersion for Igor 6.3. We *do not* do this for zmq_main_test.ipf, since the tests depend on a method that is not available in Igor6 (JSONSimple).
- In src/ZeroMQ.h, we add a #define to FV_NORETURN_TYPE if it does not exist. We need this to compile Igor6 (even though it does not really support this feature).

Other stuff:
- We add a cmake option IGOR6, to specify compilation for IGOR6/7. This modifies XOP_MINIMUM_IGOR_VERSION, as well as the default igorPath for CreateLaunchers.
- We modify where stuff is installed! If compiling with IGOR6, we put stuff in output/igor6. If IGOR6=OFF, we put stuff in output/igor8.
- We makde igorPath a cache file path variable now, so the user can modify it when compiling (via -D or cmake-gui/ccmake, depending on their operating system).

### CODE REVIEW

**Comment by nsulmol** [comment]
@t-b :

I compiled locally myself, but only for windows (I do not have a mac :( ). The zip folder was too big (70MB), so I uploaded to google drive for now. You can see it here: https://drive.google.com/file/d/13lyJvu8uPP5GqnAyntH81QSK4HpDgK4W/view?usp=sharing

Notes:
- I compiled igor8 with  "cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release -S .. -B ." and equivalent (compiling Win32 Debug/Release and x64 Debug/Release).
- I compiled igor6 with "cmake -G "Visual Studio 16 2019" -A Win32 -DIGOR6=ON -DCMAKE_BUILD_TYPE=Release -S .. -B ." and equivalent (compiling Win32 Debug/Release and x64 Debug/Release).
- You will also see a directory output/libzmq, where I have manually compiled versions of that as well. I compiled Win32 and x64 Debug and Release, with "cmake -G "NMake Makefiles" -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=OFF
-D ENABLE_CPACK=ON -D CMAKE_BUILD_TYPE=Release" (following the guidance in the INSTALL directory). I used the appropriate command line for x64 vs Win32 (e.g. x64 Native Tools Command prompt for VS 2019). These commands are different from your gitlab, and the resulting binaries are different (larger). I only message this for reference, I presume we would just use the gitlab built versions!

In all Debug compilations, I received the linker warning "LNK4098: the default 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library". I don't think it's an issue, but worth mentioning.

Thanks,
Nick

**Comment by t-b** [comment]
@nsulmol Thanks for the MR. It will take me a couple of days to have a look.

**Comment by nsulmol** [comment]
Absolutely no worries, take your time! I suspect we will want to change
things too. I simply wanted to get a reasonable 'proposal' set up on my end.

It is not a particular rush on my end, as I have the package working for my
needs :). But please let me know your thoughts to move it forward.

Thanks,
Nick

**Comment by nsulmol** [comment]
Hi @t-b ,

I just thought I would follow up, to see if you have had any time to think about this further. If you have been too busy, that's fine! I'm just setting myself semi-regular reminders so I don't lose track of this.

Thanks,
Nick

**Comment by nsulmol** [comment]
Hi @t-b ,

I hope all's well. I just wanted to follow-up, to see your thoughts on merging this in? Let me know if you'd like to talk further.

Thanks,
Nick

**Comment by t-b** [comment]
@nsulmol Sorry I did not had a look earlier. I'll plan to have a look next week.

**Comment by nsulmol** [comment]
No worries, let me know if you disagree with things (or even with the whole premise).

Thanks,
Nick

**Comment by t-b** [comment]
Review:

I think the overall direction is good. Some comments though:
- You don't need to rename the ZeroMQ constants in cpp/h files as that does not matter for IP6
- We should add the new shorter ZeroMQ constants in the ipf file in addition to the old ones. In that way we don't break existing users.
- I'm okay with moving the compilation results for `libzmq` into `output/libzmq`, but then .gitlab-ci.yml does also need adaptation
- Why do you want to have igorX folders in `output`?
- Defining `FV_NORETURN_TYPE` is the right thing to do
- ZeroMQ_Interop.ipf should also use `#pragma IgorVersion=6.37`
- I don't think we need the new IGOR6 cmake option. Converting XOP_MINIMUM_IGORVERSION to a cache variable a la 

```
set(XOP_MINIMUM_VERSION "800" CACHE STRING "Select minimum Igor Version")
```

allows us to build for IP6 with `cmake -DXOP_MINIMUM_VERSION=637 ...`. You would then user VERSION_GREATER and friends in cmake to adapt for IP6 paths.
- The rephrased error message `"ZeroMQ requires Igor Pro 6.20 or later (6.37 for Igor6)."` in .rc/.r does not make a lot of sense.

It's probably best if we rename the .r/.rc files to .r.in/.rc.in rephrase the error message `"ZeroMQ requires Igor Pro @XOP_MINIMUM_IGORVERSION@ or later."` and add 

```
CONFIGURE_FILE(ZeroMQ.r.in ZeroMQ.r @ONLY)
CONFIGURE_FILE(ZeroMQ.rc.in ZeroMQ.rc @ONLY)
```

in cmake.

For testing I've attached an JSON-XOP for IP6 to https://github.com/AllenInstitute/ZeroMQ-XOP/issues/53. Would you be interested to help out in porting the tests to use the JSON XOP instead of JSON_Simple?

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Comment by nsulmol** [comment]
Hi @t-b,

Excuse the delay! Let me make sure I get the gist of the requested changes:

> You don't need to rename the ZeroMQ constants in cpp/h files as that does not matter for IP6
We should add the new shorter ZeroMQ constants in the ipf file in addition to the old ones. In that way we don't break existing users.

Understood, I can do that and validate.

> I'm okay with moving the compilation results for libzmq into output/libzmq, but then .gitlab-ci.yml does also need adaptation
Will do. I will likely need you to validate when the CL is done, as I don't believe I have the mechanism to test this.

> Why do you want to have igorX folders in output?

I believe my initial rational was to simplify the build process (without really knowing it). I thought that it would be safer to have independent folders, so you did not risk packaging the wrong version when creating new releases.

I can revert to the prior structure, with both builds in the 'output' folder.

> Defining FV_NORETURN_TYPE is the right thing to do

Just to confirm: do you mean that what I have done currently is OK? Or would you like me to do something else?

> ZeroMQ_Interop.ipf should also use #pragma IgorVersion=6.37

Will do. I wasn't 100% sure if the pragma only allowed one minor digit, so I left it as-is originally.

> I don't think we need the new IGOR6 cmake option. Converting XOP_MINIMUM_IGORVERSION to a cache variable a la

Will do, and I will update the readme accordingly.

> I don't think we need the new IGOR6 cmake option. Converting XOP_MINIMUM_IGORVERSION to a cache variable a la [...]

Alright, good idea. I will do this as well.

> For testing I've attached an JSON-XOP for IP6 to https://github.com/AllenInstitute/ZeroMQ-XOP/issues/53. Would you be interested to help out in porting the tests to use the JSON XOP instead of JSON_Simple?

I do not require this for my purposes right now, but it may make sense soon. I will set a reminder at the beginning of summer to follow-up to scope out the amount of work needed to do it. Does that make sense to you?

Thank you,
Nick

**Comment by t-b** [comment]
>> Defining FV_NORETURN_TYPE is the right thing to do

> Just to confirm: do you mean that what I have done currently is OK? Or would you like me to do something else?

Yes this the current appraoch is good.

> I do not require this for my purposes right now, but it may make sense soon. I will set a reminder at the beginning of summer to follow-up to scope out the amount of work needed to do it. Does that make sense to you?

Sounds good!

**Comment by nsulmol** [comment]
Hi @t-b,

I made (I believe) the changes you requested in the latest commits. Note that I have not yet tested (I will be validating on Tuesday).

However, I still wanted to confirm one thing. In order to support this statement:

> We should add the new shorter ZeroMQ constants in the ipf file in addition to the old ones. In that way we don't break existing users.

In order to do this, I turn ZeroMQ_Interop.ipf into a .in file, with a preprocessor directive '#if @DECLARE_ZEROMQ_CONSTANTS_LEGACY@', which gets set up by the cmake. Without this, we run into the original error: we get a compiler error for Igor6 due to the variable length being too long for some variables. This complexifies things slightly, as we then have a 'configured' ipf file that would be put in the 'procedures' folder (or an install folder location).

Separately, I just realized that the *only* variable that is larger than the Igor6/7 length limit (31 characters) is ZeroMQ_MESSAGE_FILTER_DUPLICATED (which is 32 characters)...

So, I foresee 2 options:

1. We use the changes I have pushed, and either 'configure' the ZeroMQ_Interop.ipf.in into the top-level procedures folder or an output subdirectory (via an install() command).
2. We avoid this set of changes by simply renaming that one constant to ZeroMQ_MESSAGE_FILTER_DUPL (or some similar smaller name).

What do you think? Do you have a preference?

Thanks,
Nick

**Comment by t-b** [comment]
> In order to do this, I turn ZeroMQ_Interop.ipf into a .in file, with a preprocessor directive '#if @DECLARE_ZEROMQ_CONSTANTS_LEGACY@', which gets set up by the cmake. Without this, we run into the original error: we get a compiler error for Igor6 due to the variable length being too long for some variables. This complexifies things slightly, as we then have a 'configured' ipf file that would be put in the 'procedures' folder (or an install folder location).

Why not just do

```ipf

#if igorVersion() < 7

// short constant names

#else

// long constant names

#endif
```

?

**Comment by nsulmol** [comment]
Mostly because I'm a dummy and did not consider this. I will do this. Just note that my solution will be:

#if igorVersion() >= 8
// long constant names
#endif
// short constant names

, because I need to have the short constant names throughout (so that it compiles with igor < 7). The long constant names are here for reverse compatibility (if I understood the purpose of your original request).

Does that makes sense?

Thanks,
nick

**Comment by t-b** [comment]
You probably meant

```ipf
#if igorVersion() >= 8
// long constant names
#else
// short constant names
#endif
```

right? This is indeed more correct than my suggestion.

**Comment by nsulmol** [comment]
Hi @t-b

Actually, I meant something more like this:

`/// @name Error codes
/// @anchor ZeroMQErrorCodes
/// @{
/// Define ZeroMQ in addition to ZMQ if Igor > 8.
#if igorVersion() >= 8
   Constant ZeroMQ_UNKNOWN_SET_FLAG          = 10003
   Constant ZeroMQ_INTERNAL_ERROR            = 10004
   Constant ZeroMQ_INVALID_ARG               = 10005
   Constant ZeroMQ_HANDLER_ALREADY_RUNNING   = 10006
   Constant ZeroMQ_HANDLER_NO_CONNECTION     = 10007
   Constant ZeroMQ_MISSING_PROCEDURE_FILES   = 10008
   Constant ZeroMQ_INVALID_MESSAGE_FORMAT    = 10009
   Constant ZeroMQ_INVALID_LOGGING_TEMPLATE  = 10010
   Constant ZeroMQ_MESSAGE_FILTER_DUPLICATED = 10011
   Constant ZeroMQ_MESSAGE_FILTER_MISSING    = 10012
#endif
Constant ZMQ_UNKNOWN_SET_FLAG          = 10003
Constant ZMQ_INTERNAL_ERROR            = 10004
Constant ZMQ_INVALID_ARG               = 10005
Constant ZMQ_HANDLER_ALREADY_RUNNING   = 10006
Constant ZMQ_HANDLER_NO_CONNECTION     = 10007
Constant ZMQ_MISSING_PROCEDURE_FILES   = 10008
Constant ZMQ_INVALID_MESSAGE_FORMAT    = 10009
Constant ZMQ_INVALID_LOGGING_TEMPLATE  = 10010
Constant ZMQ_MESSAGE_FILTER_DUPLICATED = 10011
Constant ZMQ_MESSAGE_FILTER_MISSING    = 10012
/// @}
`

The point is that these constants are referenced in all the other ipfs as ZMQ_XXX. The alternative would be to have an this kind of #if / #else / #endif logic in all of the ipfs (unless I'm thinking of this poorly). Does that make sense?

And again, we could also just rename ZeroMQ_MESSAGE_FILTER_DUPLICATED, and this may all be avoided.

Thanks,
Nick

**Comment by nsulmol** [comment]
Hi @t-b

Actually, I meant something more like this:

```/// @name Error codes
/// @anchor ZeroMQErrorCodes
/// @{
/// Define ZeroMQ in addition to ZMQ if Igor > 8.
#if igorVersion() >= 8
   Constant ZeroMQ_UNKNOWN_SET_FLAG          = 10003
   Constant ZeroMQ_INTERNAL_ERROR            = 10004
   Constant ZeroMQ_INVALID_ARG               = 10005
   Constant ZeroMQ_HANDLER_ALREADY_RUNNING   = 10006
   Constant ZeroMQ_HANDLER_NO_CONNECTION     = 10007
   Constant ZeroMQ_MISSING_PROCEDURE_FILES   = 10008
   Constant ZeroMQ_INVALID_MESSAGE_FORMAT    = 10009
   Constant ZeroMQ_INVALID_LOGGING_TEMPLATE  = 10010
   Constant ZeroMQ_MESSAGE_FILTER_DUPLICATED = 10011
   Constant ZeroMQ_MESSAGE_FILTER_MISSING    = 10012
#endif
Constant ZMQ_UNKNOWN_SET_FLAG          = 10003
Constant ZMQ_INTERNAL_ERROR            = 10004
Constant ZMQ_INVALID_ARG               = 10005
Constant ZMQ_HANDLER_ALREADY_RUNNING   = 10006
Constant ZMQ_HANDLER_NO_CONNECTION     = 10007
Constant ZMQ_MISSING_PROCEDURE_FILES   = 10008
Constant ZMQ_INVALID_MESSAGE_FORMAT    = 10009
Constant ZMQ_INVALID_LOGGING_TEMPLATE  = 10010
Constant ZMQ_MESSAGE_FILTER_DUPLICATED = 10011
Constant ZMQ_MESSAGE_FILTER_MISSING    = 10012
/// @}
```

The point is that these constants are referenced in all the other ipfs as ZMQ_XXX. The alternative would be to have an this kind of #if / #else / #endif logic in all of the ipfs (unless I'm thinking of this poorly). Does that make sense?

And again, we could also just rename ZeroMQ_MESSAGE_FILTER_DUPLICATED, and this may all be avoided.

Thanks,
Nick

**Comment by t-b** [comment]
> The point is that these constants are referenced in all the other ipfs as ZMQ_XXX. The alternative would be to have an this kind of #if / #else / #endif logic in all of the ipfs (unless I'm thinking of this poorly). Does that make sense?

Yes let's do it like that!

**Comment by nsulmol** [comment]
Hi @t-b

I believe I have made all the requested changes. Once again, I don't have access to the Igor device today, so I cannot fully validate until Monday :/. I completely reverted the output directory changes, so the structure should be what it was originally. All-in-all, the CL history is a bit of a mess, as I have made and undone a lot - I'm sorry about that.

The one thing I am still uncertain on: you said

> > The point is that these constants are referenced in all the other ipfs as ZMQ_XXX. The alternative would be to have an this kind of #if / #else / #endif logic in all of the ipfs (unless I'm thinking of this poorly). Does that make sense?

> Yes let's do it like that!

But I was unsure if you meant doing #if / #endif and having the ZMQ below, or replacing every ZeroMQ constant reference with an #if / #else / #endif logic. For now, i have done the first (i.e. only ZeroMQ_Interop.ipf is changed). However, I can do the second approach if you prefer.

Thank you,
Nick

**Comment by nsulmol** [comment]
Hi @t-b,

Just as an update: I was able to confirm that the built Windows executables for this function as expected with Igor6.

I also forgot to mention another thing I noticed: aside from ZeroMQ_Interop.ipf, all the other .ipf file references to the ZeroMQ_XXX variables are in the tests. The tests do not currently work for Igor6, so if you wanted *yet another* option to mull on: we could have the #if/#else/#endif approach in the ZeroMQ_Interop.ipf only, and leave all the references in the tests as ZeroMQ_XXX. Since the tests would fail anyway, this might be acceptable. It is kicking the ball down the road, though, since presumably we will fix the tests eventually.

Thanks,
nick

**Comment by t-b** [comment]
The CI (internal only, sorry) is not happy.

Compiling on MacOSX fails with:
```
failed to find ZeroMQ/ZeroMQ.r
### Rez - noErr (0) during open of "ZeroMQ.r".
```

Looks like a `configure_file` is missing.

Other than that this is looking really good!

The commit history in this branch here would still need some tweaking. I usually create commits from logical groups. But I don't want to enforce that onto you. So I'm happy with just one commit doing everything. I can also do that (keeping you as author of course) if you are not used to this workflow and/or are not eager to use git rebase and force push.

> I also forgot to mention another thing I noticed: aside from ZeroMQ_Interop.ipf, all the other .ipf file references to the ZeroMQ_XXX variables are in the tests. The tests do not currently work for Igor6, so if you wanted yet another option to mull on: we could have the #if/#else/#endif approach in the ZeroMQ_Interop.ipf only, and leave all the references in the tests as ZeroMQ_XXX. Since the tests would fail anyway, this might be acceptable. It is kicking the ball down the road, though, since presumably we will fix the tests eventually.

The changes to the tests folder look good.

Tests are passing on IP9 on windows.

**Comment by nsulmol** [comment]
Hi @t-b,

I definitely agree with you about the commit history being a mess, so no worries about fixing it. I just went through an interactive rebase, where I tried to divide it into much more logical changes. Could you review and make sure you agree? Note that I *kept* (and split into separate commits) the changes where I modify the output structure. I didn't want to (a) break the history of this pull request, and/or (b) potentially introduce bugs by trying to remove just that part. I could squash these into their respective prior commits, but I feel that makes the commit very big...

I also pushed a small change to try and fix the APPLE build error. I think/hope it was just due to not indicating that this file is generated via SET_SOURCE_FILE_PROPERTIES( ... GENERATED TRUE).

Let me know what you think / what your test suite finds.

Thanks,
Nick

**Comment by nsulmol** [comment]
Hi @t-b,

Just a ping: is this OK to merge in?

Thanks,
Nick

**Comment by t-b** [comment]
@nsulmol I've pushed a commit which fixes compilation on MacOSX. And now everything looks good! Thanks a lot for you contribution and your patience.

**Review by t-b — APPROVED** [review]

**Comment by nsulmol** [comment]
Hi @t-b,

Thank you for your time and help working through this. I'm happy it can go into the official repo, in case it is useful for someone else!

Thanks,
Nick

**Pull request merged**
