### PR TITLE
Update readme.rst for Compilations Instructions

### PR DESCRIPTION
**Pull request by nsulmol**
While trying to compile from source, I realized there were additional 3rd party dependencies not highlighted in the readme. I modified the readme to be up-to-date.

Note: I made a minor change in the CMakeLists, changing where we expect cmake-modules to be.

### CODE REVIEW

**Comment by t-b** [comment]
Thanks for the PR. I'm a bit confused about the dependencies you mention. Did you clone the repo with `--recurse-submodules`? If yes json, fmt and the cmake code should be already there. If you want to pull in the submodules from an existing clone `git submodule update --init` should do the job.

**Comment by nsulmol** [comment]
Hello t-b,

Indeed, I did not! I must apologize - I was unaware of the --recursive-submodules aspect, and had just done a simple git clone. Properly recursing submodules clones stuff I did not even notice.

Evidently, I was unaware of this. I should have noticed it since there is a .gitmodules file (and empty folders)!

Do you think it is worth expliciting that you should cloen with --recurse-submodules (or use git submodule update --init --recursive) in the readme? This may be obvious to most git users, and was just a newbie mistake on my part.

I can cancel this pull request, excuse me for that.

Thanks,
Nick

**Comment by nsulmol** [comment]
As a minor addendum here: I was clearly wrong/forgot about the submodules. However, it still does not explicit that you must copy the XOPSupport folder from your XOPToolkit, right (or symbolic link it)?

**Comment by t-b** [comment]
@nsulmol 

> Do you think it is worth expliciting that you should clone with --recurse-submodules (or use git submodule update --init --recursive) in the readme? 

Yes I think so, this is worth mentioning.

In this PR you added

```
After install, the created libraries will be located in $zmq-xop-dir/output/$os, where $os is mac for Mac, and win for Windows. For Mac, they will be in an xop directory, whereas for Windows they will be in an xop directory *within* a 'bitness' directory (x64 for 64-bit, x86 for 32-bit).
```

and I think this is worth having.

The changes to the build steps are also worth having, but please keep the comments about Visual Studio and its prompt.

> However, it still does not explicit that you must copy the XOPSupport folder from your XOPToolkit, right (or symbolic link it)?

Yes we should mention that as well.

**Comment by t-b** [comment]
Reopened.

**Pull request closed without merging**
